name: hovernet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda-pack=0.6.0
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gdal=1.9.2
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=72.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libhwloc=2.9.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.5
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - ncurses=6.4.20240210
  - nettle=3.7.3
  - networkx=2.8.4
  - openh264=2.1.1
  - openjdk=8.0.152
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openssl=3.2.1
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python_abi=3.9=4_cp39
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0=cuda
  - readline=8.2
  - requests=2.29.0
  - setuptools=67.8.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - urllib3=1.26.15
  - wheel=0.38.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiobotocore
      - aiohttp==3.9.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - albumentations==1.3.1
      - anndata
      - annotated-types==0.6.0
      - anyio==4.3.0
      - app-model==0.2.6
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.6
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blessed==1.20.0
      - boto3==1.34.69
      - botocore
      - build==1.2.1
      - cached-property==1.5.2
      - cachey==0.2.1
      - cell2location==0.1.3
      - chex==0.1.7
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - croniter==2.0.5
      - cycler==0.12.1
      - cython==3.0.10
      - dask==2024.2.1
      - dask-expr
      - dask-image==2023.8.1
      - datashader==0.16.1
      - datashape==0.5.2
      - dateutils==0.6.12
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepdiff==7.0.1
      - defusedxml==0.7.1
      - distributed
      - dm-tree==0.1.8
      - docrep==0.3.2
      - docstring-parser==0.16
      - docutils==0.20.1
      - editor==1.6.6
      - entrypoints==0.4
      - etils==1.5.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastapi==0.110.2
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fcsparser==0.2.8
      - fiona==1.9.6
      - flax==0.7.4
      - fonttools==4.51.0
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - future==1.0.0
      - geopandas==0.14.3
      - greenlet==3.0.3
      - h11==0.14.0
      - h5py==3.11.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - huggingface-hub==0.22.2
      - igraph==0.11.4
      - imagecodecs==2024.1.1
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - in-n-out==0.2.0
      - inflect==7.2.0
      - inquirer==3.2.4
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jax==0.4.13
      - jaxlib==0.4.13
      - jedi==0.19.1
      - jmespath==1.0.1
      - joblib==1.4.0
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-cache==0.6.1
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-lsp==2.2.0
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.22.1
      - kiwisolver==1.4.5
      - lamin-utils==0.13.2
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - lightning==2.1.4
      - lightning-cloud==0.5.66
      - lightning-utilities==0.11.2
      - llvmlite
      - locket==1.0.0
      - loguru==0.7.2
      - magicgui==0.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.8.1
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.4.0
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - mudata==0.2.3
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multiscale-spatial-image==0.11.2
      - mypy-extensions==1.0.0
      - myst-nb==1.1.0
      - myst-parser==2.0.0
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-matplotlib==2.0.1
      - napari-plugin-engine==0.2.0
      - napari-spatialdata==0.4.1
      - napari-svg==0.1.10
      - natsort==8.4.0
      - nbclient==0.7.4
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - npe2==0.7.5
      - numba
      - numcodecs==0.12.1
      - numpy
      - numpydoc==1.7.0
      - numpyro==0.12.1
      - ome-zarr==0.8.3
      - omnipath==1.0.8
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - openslide-python==1.3.1
      - opt-einsum==3.3.0
      - optax==0.2.1
      - orbax-checkpoint==0.5.9
      - ordered-set==4.1.0
      - overrides==7.7.0
      - packaging==24.0
      - pandas
      - pandocfilters==1.5.1
      - param==2.1.0
      - parso==0.8.4
      - partd==1.4.1
      - pathml==2.1.1
      - patsy==0.5.6
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pims==0.6.1
      - pint==0.23
      - platformdirs==4.2.0
      - pooch==1.8.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==5.26.1
      - psutil==5.9.8
      - psygnal==0.11.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.0.0
      - pyconify==0.1.6
      - pyct==0.5.0
      - pydantic==2.7.0
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.1
      - pydicom==2.4.4
      - pygeos==0.14
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pynndescent==0.5.12
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyproject-hooks==1.0.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - pyrsistent==0.20.0
      - python-bioformats==4.0.7
      - python-dateutil==2.9.0.post0
      - python-editor==1.0.4
      - python-igraph==0.11.4
      - python-javabridge==4.0.3
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytomlpp==1.0.13
      - pytorch-lightning==2.2.2
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==26.0.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - qudida==0.0.4
      - readchar==4.0.6
      - readfcs==1.1.8
      - referencing==0.34.0
      - regex==2024.4.16
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - runs==1.2.2
      - s3fs
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - scanpy==1.9.3
      - scikit-image
      - scikit-learn==1.4.2
      - scipy
      - scvi-tools==1.1.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - shapely==2.0.4
      - shellingham==1.5.4
      - simpleitk==2.3.1
      - six==1.16.0
      - slicerator==1.1.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spams==2.6.5.4
      - sparse==0.15.1
      - spatial-image==0.3.0
      - spatialdata==0.1.2
      - spatialdata-io==0.1.2
      - spatialdata-plot==0.2.1
      - sphinx==7.3.7
      - sphinx-copybutton==0.5.2
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.29
      - squidpy==1.2.2
      - stack-data==0.6.3
      - starlette==0.37.2
      - starsessions==2.1.3
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - superqt==0.6.3
      - tabulate==0.9.0
      - tangram-sc==1.0.4
      - tblib==3.0.0
      - tensorstore==0.1.56
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.4.0
      - tifffile==2024.4.18
      - timm==0.9.16
      - tinycss2==1.2.1
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - torchinfo==1.8.0
      - torchmetrics==1.3.2
      - torchstain==1.3.0
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.3
      - transformers==4.40.0
      - typeguard==4.2.1
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - uvicorn==0.29.0
      - validators==0.28.1
      - vispy==0.14.2
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - wrapt==1.16.0
      - xarray
      - xarray-dataclasses
      - xarray-datatree
      - xarray-schema==0.0.3
      - xarray-spatial==0.3.7
      - xmod==1.8.1
      - yarl==1.9.4
      - zarr==2.17.2
      - zict==3.0.0
      - zipp==3.18.1
prefix: /scratch/project_mnt/S0010/Andrew_N/conda/hovernet